version: "3.7"
services:
  backend:
    build: .
    ports:
      - "80:80"
    environment:
       "ASPNETCORE_ENVIRONMENT": "Development"
       "ConnectionStrings__Initial": "Host=db;Port=5432;User Id=postgres;Password=password;Database=postgres;Pooling=true"
       "ConnectionStrings__Default": "Host=db;Port=5432;User Id=postgres;Password=password;Database=postgres;Pooling=true"
    depends_on:
      - db
    restart: "on-failure"
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

volumes:
  data:
  